# Site settings
title: "Ameya's blog"
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  "Ameya's trysts with technology"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://juggernaut.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  juggernaut

# Build settings
markdown: kramdown
future: true
#plugins:
#  - jekyll-time-to-read
